### ISSUE TITLE
Depreciate this buildpack in favour of cloudfoundry-community/staticfile-buildpack

### ISSUE THREAD

**Issue by mrdavidlaing** [cloudfoundry-community/nginx-buildpack#15]
https://github.com/cloudfoundry-community/staticfile-buildpack seems to be a functional improvement on hosting static websites on CF, and has a much better name.

Perhaps this buildpack should be depreciated in favour of using the staticfile-buildpack

**Comment by mrdavidlaing** [comment]
@drnic - you agree?

**Comment by drnic** [comment]
Ok

**Comment by drnic** [comment]
Sorry! :)
