### ISSUE TITLE
Don't upload / server manifest.yml / stackato.yml

### ISSUE THREAD

**Issue by mrdavidlaing** [cloudfoundry-community/nginx-buildpack#4]
Currently `manifest.yml` and `stackato.yml` get uploaded and placed in the public folder, making it possible to download them; a potential security issue.

eg:  http://simple_site.cfapps.io/manifest.yml

This should be prevented by either:
1.  Not uploading them
2.  Removing them from the public/ folder
3.  Having nginx config that prevents downloading these files.

**Comment by mrdavidlaing** [comment]
@andypiper - Do you have any idea which of these options is best?

I'm leaning towards 3

**Comment by andypiper** [comment]
I don't see why any yml files should be served up - we're already specifying that this is for static HTML sites. Having said that, a user _might_ have included such a file for a reason. Not uploading them would require cf to know not to do so AFAICT. I think 2 or 3 are good options, my preference being 2.

**Comment by mrdavidlaing** [comment]
A use case for when you want to host .yml files - http://download.pivotal.io.s3.amazonaws.com/openjdk/lucid/x86_64/index.yml

2 is actually easier; I'll implement that

**Comment by mrdavidlaing** [comment]
Resolved by 24da3a07d861b36df319654e1bac74ec1629a3f4
