### ISSUE TITLE
nginx buildpack does not work anymore due to missing dl link

### ISSUE THREAD

**Issue by soudmaijer** [cloudfoundry-community/nginx-buildpack#8]
nginx buildpack does not work anymore due to missing dl link

compile_nginx_download=https://d35wldypfbhn1h.cloudfront.net/nginx-1.4.1.tar.gz

Please put it somewhere where it is available :-)

**Comment by andypiper** [comment]
huh, weird, I used it successfully about 2 days ago, this must be a recent change.

**Comment by soudmaijer** [comment]
Yes it is. We noticed that has been failing since yesterday

**Comment by ghost** [comment]
Damn...that hurts! Any alternative download locations for the file? We need it badly

**Comment by soudmaijer** [comment]
Why not replace the download link with the real nginx download link?

http://nginx.org/download/nginx-${NGINX_VERSION}.tar.gz

Or is there some magic in the provide download url?

**Comment by ghost** [comment]
I actually tried the trick with the alternate download location on a fork. But it did not work. Maybe I did something wrong.

**Comment by ghost** [comment]
The tar downloaded from nginx.org does not contain the binaries in /sbin. Any idea where I can get a tar containing these binaries?

**Comment by soudmaijer** [comment]
Jan, the buildpack expects the tar file to contain the compiled nginx binaries. My trick with the actual sources does not work.

**Comment by soudmaijer** [comment]
I am building a new version of nginx. Testing it right now. 

I am using a vagrant box to build the package:

```
  config.vm.box_url = "http://files.vagrantup.com/lucid64.box"
```

My build script:

```
# http://jamie.curle.io/blog/compiling-nginx-ubuntu/

sudo su
apt-get -f -y install build-essential libpcre3 libpcre3-dev zlib1g-dev

mkdir ~/src
cd ~/src
nginx_version=1.4.3
wget http://nginx.org/download/nginx-$nginx_version.tar.gz
tar -xvzf nginx-$nginx_version.tar.gz 
cd nginx-$nginx_version
./configure

make 
make install

cd /usr/local
tar -zcvpf ~/nginx-1.4.3.tar.gz nginx/
```

**Comment by soudmaijer** [comment]
Tested my package and it works!

**Comment by soudmaijer** [comment]
Thanks!
